POST http://localhost:3001/person
Content-Type: application/json

{
    "firstName": "Zhong",
    "lastName": "Dai",
    "email": "123xyz@gmail.com"
}

###

GET http://localhost:3001/person


###
GET http://localhost:3001/person/2
